### ISSUE TITLE
Hooks do not apply for realtime events

### ISSUE THREAD

**Issue by Mangatt** [feathersjs/feathers#376]
Hi,
I've just found that hooks do not apply for realtime events. Following code will remove password field from service response.

`app.service('users').after({
    all: hooks.remove('password'),
});`

But when entry is updated, whole entry is emmited through updated event, even with password field.

Are there any plans for unifiying filters for both service methods and realtime events or is there any workaround?

**Comment by marshallswain** [comment]
Hi @Mangatt, can you post your initial server setup?  Hooks should work universally across all providers.  Maybe there's a problem with the order you're initializing the plugins.

**Comment by daffl** [comment]
This used to be issue https://github.com/feathersjs/feathers/issues/248 which was fixed a while ago via https://github.com/feathersjs/feathers-hooks/pull/57 (test in https://github.com/feathersjs/feathers-hooks/blob/c0a13f1c7b05135d9b67627c3c60c0965ac71b17/test/hooks.test.js#L47).

Are you using `feathers-hooks` 1.4.0 or later?

**Comment by Mangatt** [comment]
I'm using feathers-hooks 1.5.4. My setup is:

const app = feathers();

app.configure(configuration(__dirname, '../config'))
	.use('/', serveStatic(app.get('public')))
	.configure(rest())
	.configure(socketio())
	.configure(hooks())
	.use(bodyParser.json())
	.use(bodyParser.urlencoded({ extended: true }))
	.configure(auth(app.get('auth')))
	.configure(users)
	.configure(locations)
	.configure(messages);

app.use('/users', service({
	Model: rethink,
	name: 'users'
}));
	
app.service('users').after({
	all: hooks.remove('password'),
});

Can you see a problem there?

**Comment by marshallswain** [comment]
Can you try moving hooks first, before the providers.

**Comment by Mangatt** [comment]
Even with changed order problem persists:

app.configure(configuration(__dirname, '../config'))
	.use('/', serveStatic(app.get('public')))
	.configure(hooks())
	.configure(rest())
	.configure(socketio())
	.use(bodyParser.json())
	.use(bodyParser.urlencoded({ extended: true }))
	.configure(auth(app.get('auth')))
	.configure(users)
	.configure(locations)
	.configure(messages);

**Comment by daffl** [comment]
One thing to note is that the standard `remove` hook will only run for external calls so events from internal calls to the service will be dispatched with the full data. One way to solve the issue is to add an [event filter](http://docs.feathersjs.com/real-time/filtering.html) that always removes the data:

```js
const omit = require('lodash.omit');

app.service('users').filter(data => omit(data, 'password'));
```

It might be a good idea to make the hooks where it applies (like `remove`) to also run as the correct event filters.

**Comment by Mangatt** [comment]
That would be great. Filtering at two places create unnecessary margin for errors.

**Comment by daffl** [comment]
Right now there is not really a way around that. We can't always remove the password since then we can't compare it.

What I meant was being able to do something like `app.service('users').filter(hooks.remove('password'));`

**Comment by daffl** [comment]
I keep wondering what would be a good way to solve this (not having to duplicate filters and hooks). Filters are very similar to hooks (https://github.com/feathersjs/feathers-socket-commons/issues/4 is related) but I think only a few hooks also apply to filters.

@ekryski and I were talking about that events and event filtering could even be applied as a hook. That way hooks that conditionally run (like `pluck`, `disable` could run either way and add the result to the hook object which will then be dispatched by the filter).

**Comment by ekryski** [comment]
💯  @daffl having the event dispatch and filtering happen as the last hooks in the hook chain I think would solve this. We would no longer need filters and then you can be gauranteed that the state of your hook is what gets sent to your dispatcher.

**Comment by marshallswain** [comment]
That sounds good.  That will make it so you opt in to events by needing to add a handler at the end.

**Comment by subodhpareek18** [comment]
What this will also be great for is linked data. Currently the hooks like `include` and `$populate` work fine on normal api calls, but when a resource updates it no longer contains the linked data. 

If all the other hooks run before for sure, then it will make things much less confusing. And make frontend development really consistent as you don't need to worry about the different behaviour for the first snapshot call and subsequent realtime updates.

**Comment by jakobrosenberg** [comment]
So is this fixed/implemented in v3? If so, it's not working for me.

**Comment by daffl** [comment]
Yes but for protecting fields you have to use the [protect hook](https://buzzard.docs.feathersjs.com/migrating.html#protecting-fields).

**Comment by jakobrosenberg** [comment]
I created a simple hook.

```
  after: {
    all: [],
    find: [
      (ctx)=>{
        ctx.result.data = ctx.result.data.map(doc => {
          doc.name = doc.name+'!!!'
          return doc
        })
      }
    ],
```

As you can see it suffixes the name with ``!!!`` and it works in the find function, but not in the subsequent real-time results.

**Comment by jakobrosenberg** [comment]
Upon further investigation, it seems only the all hook is called on realtime updates.

**Comment by daffl** [comment]
Do you have a reproducable example? I just added

```js
app.service('messages').hooks({
  after: {
    create(context) {
      context.result.name = 'Test';
    }
  }
});
```

To the example from the [homepage](https://feathersjs.com/) and it does what I'd expect.

**Comment by jakobrosenberg** [comment]
My mistake was applying the hook to the ``find`` event. It should have been applied to ``all`` instead.

Are you guys on gitter or similar?

**Comment by daffl** [comment]
You can get in touch via [Slack](http://slack.feathersjs.com/), [Twitter](twitter.com/feathersjs) and ask questions on Github and [Stackoverflow](https://stackoverflow.com/questions/tagged/feathersjs).
